DROP TABLE ADMINISTRADOR;
DROP TABLE CLIENTE;
DROP TABLE CUENTA;
DROP TABLE REPORTES;
DROP TABLE TIPOCUENTA;

CREATE TABLE ADMINISTRADOR (
    ID               NUMBER(19, 0)
        NOT NULL ENABLE,
    CLAVE            VARCHAR2(255 CHAR)
        NOT NULL ENABLE,
    DOCUMENTO        VARCHAR2(255 CHAR)
        NOT NULL ENABLE,
    NOMBRE           VARCHAR2(255 CHAR)
        NOT NULL ENABLE,
    TIPO_DOCUMENTO   VARCHAR2(255 CHAR)
        NOT NULL ENABLE,
    PRIMARY KEY ( ID )
);

CREATE TABLE CLIENTE (
    DOCUMENTO        VARCHAR2(255 CHAR)
        NOT NULL ENABLE,
    TIPO_DOCUMENTO   VARCHAR2(255 CHAR)
        NOT NULL ENABLE,
    CLAVE            VARCHAR2(255 CHAR),
    ESTADO           NUMBER(1, 0)
        NOT NULL ENABLE,
    PRIMARY KEY ( DOCUMENTO,
                  TIPO_DOCUMENTO )
);

CREATE TABLE CUENTA (
    ID               NUMBER(19, 0)
        NOT NULL ENABLE,
    ESTADO           NUMBER(1, 0)
        NOT NULL ENABLE,
    SALDO            FLOAT(126)
        NOT NULL ENABLE,
    TIPO_DOCUMENTO   VARCHAR2(255 CHAR),
    DOCUMENTO        VARCHAR2(255 CHAR),
    ID_TIPO_CUENTA   NUMBER(19, 0),
    PRIMARY KEY ( ID )
);

CREATE TABLE REPORTES (
    ID                NUMBER(19, 0)
        NOT NULL ENABLE,
    CANTIDAD          FLOAT(126)
        NOT NULL ENABLE,
    FECHA             TIMESTAMP(6),
    TIPO_MOVIMIENTO   VARCHAR2(255 CHAR),
    TIPO_DOCUMENTO    VARCHAR2(255 CHAR),
    DOCUMENTO         VARCHAR2(255 CHAR),
    PRIMARY KEY ( ID )
);

CREATE TABLE TIPOCUENTA (
    ID       NUMBER(19, 0)
        NOT NULL ENABLE,
    NOMBRE   VARCHAR2(255 CHAR),
    PRIMARY KEY ( ID )
);

INSERT INTO ADMINISTRADOR (ID, CLAVE, DOCUMENTO, NOMBRE, TIPO_DOCUMENTO) VALUES ('01', 'eSDt7jgjW6mpP034ZXiq/g==', '1024', 'Juan', 'C');
INSERT INTO ADMINISTRADOR (ID, CLAVE, DOCUMENTO, NOMBRE, TIPO_DOCUMENTO) VALUES ('02', '35U9N3ucGr+aRAfMoV+7dA==', '1026', 'Pedro', 'C');
INSERT INTO ADMINISTRADOR (ID, CLAVE, DOCUMENTO, NOMBRE, TIPO_DOCUMENTO) VALUES ('03', 'AiHW0/D7cfOMtgxWXBZGYg==', '1025', 'Martha', 'C');
INSERT INTO ADMINISTRADOR (ID, CLAVE, DOCUMENTO, NOMBRE, TIPO_DOCUMENTO) VALUES ('04', 'lFdI399m6GOhtHW99wYWrA==', '452', 'Maria', 'E');
INSERT INTO ADMINISTRADOR (ID, CLAVE, DOCUMENTO, NOMBRE, TIPO_DOCUMENTO) VALUES ('05', '300aJq1K9dkYfoDN5cFvIw==', '12456', 'Carlos', 'T');

INSERT INTO TIPOCUENTA (ID, NOMBRE) VALUES ('1', 'CUENTA DE AHORROS');
INSERT INTO TIPOCUENTA (ID, NOMBRE) VALUES ('2', 'CUENTA HIPOTECARIA');
INSERT INTO TIPOCUENTA (ID, NOMBRE) VALUES ('3', 'CUENTA CORRIENTE');
INSERT INTO TIPOCUENTA (ID, NOMBRE) VALUES ('4', 'TARJETA DE CREDITO');


INSERT INTO CLIENTE (DOCUMENTO, TIPO_DOCUMENTO, CLAVE, ESTADO) VALUES ('1475', 'C', 'qIYMeYp6tivELHsO065wJQ==', '1');
INSERT INTO CLIENTE (DOCUMENTO, TIPO_DOCUMENTO, CLAVE, ESTADO) VALUES ('1569', 'E', 'wDi8KAwPz99mkF0RDRlllA==', '0');
INSERT INTO CLIENTE (DOCUMENTO, TIPO_DOCUMENTO, CLAVE, ESTADO) VALUES ('1258', 'P', 'Uv86lWFKxHVhTVmrbNIBnA==', '1');
INSERT INTO CLIENTE (DOCUMENTO, TIPO_DOCUMENTO, CLAVE, ESTADO) VALUES ('1479', 'C', 'wFmbzGs7Cmdvq80oi1h0dg==', '1');
INSERT INTO CLIENTE (DOCUMENTO, TIPO_DOCUMENTO, CLAVE, ESTADO) VALUES ('1332', 'C', 'QqOFPF/d5bUb+QA7Sp/7EA==', '0');


INSERT INTO CUENTA (ID, ESTADO, SALDO, DOCUMENTO, TIPO_DOCUMENTO, ID_TIPO_CUENTA) VALUES ('1', '1', '2569', '1479', 'C', '2');
INSERT INTO CUENTA (ID, ESTADO, SALDO, DOCUMENTO, TIPO_DOCUMENTO, ID_TIPO_CUENTA) VALUES ('2', '1', '2365', '1475', 'C', '1');
INSERT INTO CUENTA (ID, ESTADO, SALDO, DOCUMENTO, TIPO_DOCUMENTO, ID_TIPO_CUENTA) VALUES ('3', '0', '25485', '1258', 'P', '3');


INSERT INTO REPORTES (ID, CANTIDAD, TIPO_MOVIMIENTO, DOCUMENTO, TIPO_DOCUMENTO) VALUES ('1', '1526', 'EGRESO', '1479', 'C');
INSERT INTO REPORTES (ID, CANTIDAD, TIPO_MOVIMIENTO, DOCUMENTO, TIPO_DOCUMENTO) VALUES ('2', '2589', 'EGRESO', '1475', 'C');
INSERT INTO REPORTES (ID, CANTIDAD, TIPO_MOVIMIENTO, DOCUMENTO, TIPO_DOCUMENTO) VALUES ('3', '12000', 'INGRESO', '1479', 'C');
INSERT INTO REPORTES (ID, CANTIDAD, TIPO_MOVIMIENTO, DOCUMENTO, TIPO_DOCUMENTO) VALUES ('4', '15489', 'INGRESP', '1475', 'C');
